name: lora_trainer_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.9.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.0.1
      - bitsandbytes==0.48.2
      - brotli==1.1.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - deepspeed==0.17.4
      - diffusers==0.36.0.dev0
      - dill==0.3.8
      - einops==0.8.0
      - exceptiongroup==1.3.0
      - fastapi==0.120.2
      - ffmpy==0.6.4
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.3
      - ninja==1.13.0
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - onnxruntime==1.22.1
      - opencv-python==4.12.0.88
      - optimum-quanto==0.2.7
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - pandas-stubs==2.3.2.250926
      - peft==0.17.0
      - pillow==11.3.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.11
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.2
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.49.1
      - sympy==1.14.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - tomlkit==0.13.3
      - torch==2.7.1
      - torchaudio==2.5.1+cu121
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.55.0
      - triton==3.3.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/anconda3/envs/lora_trainer_env
